name: Test and deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Deps
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg lsb-release perl

      - name: Install OpenResty
        run: |
          wget -O - https://openresty.org/package/pubkey.gpg | sudo gpg --dearmor -o /usr/share/keyrings/openresty.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/openresty.gpg] http://openresty.org/package/ubuntu $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/openresty.list > /dev/null
          sudo apt-get update
          sudo apt-get install -y openresty libtest-nginx-perl

      - name: Test!
        run: make test

      - name: Deploy to "production" branch
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: |
          rm -rf /tmp/out && mkdir -p /tmp/out
          cp lib/resty/limit/*.lua /tmp/out/
          git config --global user.email "noreply@github.com"
          git config --global user.name "GitHub Actions"
          if git ls-remote --exit-code --heads origin production; then
            git checkout production
          else
            git checkout --orphan production
            git rm -rf .
          fi
          rm -rf t/
          mv /tmp/out/* .
          git add .
          git commit -m "Deployed from GitHub Actions"
          git push origin production
